// Full cross-platform emoji set (Emoji 12.0 compatible - iOS & Android)
// Organized by category like the iPhone emoji picker

export interface EmojiCategory {
  name: string
  icon: string
  emojis: { emoji: string; keywords: string }[]
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    name: 'Smileys',
    icon: '😀',
    emojis: [
      { emoji: '😀', keywords: 'grinning face happy smile' },
      { emoji: '😃', keywords: 'grinning face big eyes happy' },
      { emoji: '😄', keywords: 'grinning face smiling eyes happy' },
      { emoji: '😁', keywords: 'beaming face smiling eyes grin' },
      { emoji: '😆', keywords: 'grinning squinting face laugh' },
      { emoji: '😅', keywords: 'grinning face sweat nervous' },
      { emoji: '🤣', keywords: 'rolling floor laughing rofl' },
      { emoji: '😂', keywords: 'face tears joy laugh cry' },
      { emoji: '🙂', keywords: 'slightly smiling face' },
      { emoji: '🙃', keywords: 'upside down face silly' },
      { emoji: '😉', keywords: 'winking face flirt' },
      { emoji: '😊', keywords: 'smiling face smiling eyes blush' },
      { emoji: '😇', keywords: 'smiling face halo angel innocent' },
      { emoji: '🥰', keywords: 'smiling face hearts love' },
      { emoji: '😍', keywords: 'smiling face heart eyes love' },
      { emoji: '🤩', keywords: 'star struck excited amazing' },
      { emoji: '😘', keywords: 'face blowing kiss love' },
      { emoji: '😗', keywords: 'kissing face' },
      { emoji: '☺️', keywords: 'smiling face relaxed' },
      { emoji: '😚', keywords: 'kissing face closed eyes' },
      { emoji: '😙', keywords: 'kissing face smiling eyes' },
      { emoji: '🥲', keywords: 'smiling face tear happy sad' },
      { emoji: '😋', keywords: 'face savoring food yum delicious' },
      { emoji: '😛', keywords: 'face tongue playful' },
      { emoji: '😜', keywords: 'winking face tongue crazy' },
      { emoji: '🤪', keywords: 'zany face crazy wild' },
      { emoji: '😝', keywords: 'squinting face tongue' },
      { emoji: '🤑', keywords: 'money mouth face rich' },
      { emoji: '🤗', keywords: 'hugging face hug' },
      { emoji: '🤭', keywords: 'face hand over mouth giggle' },
      { emoji: '🤫', keywords: 'shushing face quiet secret' },
      { emoji: '🤔', keywords: 'thinking face hmm wonder' },
      { emoji: '🤐', keywords: 'zipper mouth face quiet' },
      { emoji: '🤨', keywords: 'face raised eyebrow skeptical' },
      { emoji: '😐', keywords: 'neutral face meh' },
      { emoji: '😑', keywords: 'expressionless face blank' },
      { emoji: '😶', keywords: 'face without mouth silent' },
      { emoji: '😏', keywords: 'smirking face smug' },
      { emoji: '😒', keywords: 'unamused face annoyed' },
      { emoji: '🙄', keywords: 'face rolling eyes whatever' },
      { emoji: '😬', keywords: 'grimacing face awkward' },
      { emoji: '🤥', keywords: 'lying face pinocchio' },
      { emoji: '😌', keywords: 'relieved face calm peaceful' },
      { emoji: '😔', keywords: 'pensive face sad thoughtful' },
      { emoji: '😪', keywords: 'sleepy face tired' },
      { emoji: '🤤', keywords: 'drooling face want desire' },
      { emoji: '😴', keywords: 'sleeping face zzz tired' },
      { emoji: '😷', keywords: 'face medical mask sick' },
      { emoji: '🤒', keywords: 'face thermometer sick fever' },
      { emoji: '🤕', keywords: 'face head bandage hurt injury' },
      { emoji: '🤢', keywords: 'nauseated face sick gross' },
      { emoji: '🤮', keywords: 'face vomiting sick puke' },
      { emoji: '🤧', keywords: 'sneezing face sick cold' },
      { emoji: '🥵', keywords: 'hot face sweating heat' },
      { emoji: '🥶', keywords: 'cold face freezing' },
      { emoji: '🥴', keywords: 'woozy face drunk dizzy' },
      { emoji: '😵', keywords: 'dizzy face unconscious' },
      { emoji: '🤯', keywords: 'exploding head mind blown shocked' },
      { emoji: '🤠', keywords: 'cowboy hat face western' },
      { emoji: '🥳', keywords: 'partying face celebration birthday' },
      { emoji: '🥸', keywords: 'disguised face glasses mustache' },
      { emoji: '😎', keywords: 'smiling face sunglasses cool' },
      { emoji: '🤓', keywords: 'nerd face glasses smart' },
      { emoji: '🧐', keywords: 'face monocle curious fancy' },
      { emoji: '😕', keywords: 'confused face puzzled' },
      { emoji: '😟', keywords: 'worried face concern' },
      { emoji: '🙁', keywords: 'slightly frowning face sad' },
      { emoji: '☹️', keywords: 'frowning face sad unhappy' },
      { emoji: '😮', keywords: 'face open mouth surprised' },
      { emoji: '😯', keywords: 'hushed face surprised quiet' },
      { emoji: '😲', keywords: 'astonished face shocked amazed' },
      { emoji: '😳', keywords: 'flushed face embarrassed' },
      { emoji: '🥺', keywords: 'pleading face puppy eyes please' },
      { emoji: '😦', keywords: 'frowning face open mouth' },
      { emoji: '😧', keywords: 'anguished face distressed' },
      { emoji: '😨', keywords: 'fearful face scared afraid' },
      { emoji: '😰', keywords: 'anxious face sweat worried' },
      { emoji: '😥', keywords: 'sad but relieved face' },
      { emoji: '😢', keywords: 'crying face sad tear' },
      { emoji: '😭', keywords: 'loudly crying face sob' },
      { emoji: '😱', keywords: 'face screaming fear scared' },
      { emoji: '😖', keywords: 'confounded face frustrated' },
      { emoji: '😣', keywords: 'persevering face struggling' },
      { emoji: '😞', keywords: 'disappointed face sad' },
      { emoji: '😓', keywords: 'downcast face sweat' },
      { emoji: '😩', keywords: 'weary face tired exhausted' },
      { emoji: '😫', keywords: 'tired face exhausted' },
      { emoji: '🥱', keywords: 'yawning face tired sleepy' },
      { emoji: '😤', keywords: 'face steam nose angry huffing' },
      { emoji: '😡', keywords: 'pouting face angry red' },
      { emoji: '😠', keywords: 'angry face mad' },
      { emoji: '🤬', keywords: 'face symbols mouth swearing' },
      { emoji: '😈', keywords: 'smiling face horns devil' },
      { emoji: '👿', keywords: 'angry face horns devil' },
      { emoji: '💀', keywords: 'skull dead death' },
      { emoji: '☠️', keywords: 'skull crossbones death danger' },
      { emoji: '💩', keywords: 'pile poo poop' },
      { emoji: '🤡', keywords: 'clown face circus' },
      { emoji: '👹', keywords: 'ogre monster japanese' },
      { emoji: '👺', keywords: 'goblin monster japanese' },
      { emoji: '👻', keywords: 'ghost spooky halloween' },
      { emoji: '👽', keywords: 'alien extraterrestrial ufo' },
      { emoji: '👾', keywords: 'alien monster space invader' },
      { emoji: '🤖', keywords: 'robot face machine' },
      { emoji: '😺', keywords: 'grinning cat happy' },
      { emoji: '😸', keywords: 'grinning cat smiling eyes' },
      { emoji: '😹', keywords: 'cat tears joy laugh' },
      { emoji: '😻', keywords: 'smiling cat heart eyes love' },
      { emoji: '😼', keywords: 'cat wry smile smug' },
      { emoji: '😽', keywords: 'kissing cat' },
      { emoji: '🙀', keywords: 'weary cat shocked' },
      { emoji: '😿', keywords: 'crying cat sad' },
      { emoji: '😾', keywords: 'pouting cat angry' },
      { emoji: '🙈', keywords: 'see no evil monkey' },
      { emoji: '🙉', keywords: 'hear no evil monkey' },
      { emoji: '🙊', keywords: 'speak no evil monkey' },
    ],
  },
  {
    name: 'Gestures',
    icon: '👋',
    emojis: [
      { emoji: '👋', keywords: 'waving hand hello goodbye' },
      { emoji: '🤚', keywords: 'raised back hand stop' },
      { emoji: '🖐️', keywords: 'hand splayed fingers' },
      { emoji: '✋', keywords: 'raised hand stop high five' },
      { emoji: '🖖', keywords: 'vulcan salute spock' },
      { emoji: '👌', keywords: 'ok hand okay perfect' },
      { emoji: '🤌', keywords: 'pinched fingers italian' },
      { emoji: '🤏', keywords: 'pinching hand small little' },
      { emoji: '✌️', keywords: 'victory hand peace' },
      { emoji: '🤞', keywords: 'crossed fingers luck hope' },
      { emoji: '🤟', keywords: 'love you gesture hand' },
      { emoji: '🤘', keywords: 'sign horns rock metal' },
      { emoji: '🤙', keywords: 'call me hand shaka' },
      { emoji: '👈', keywords: 'backhand index pointing left' },
      { emoji: '👉', keywords: 'backhand index pointing right' },
      { emoji: '👆', keywords: 'backhand index pointing up' },
      { emoji: '🖕', keywords: 'middle finger' },
      { emoji: '👇', keywords: 'backhand index pointing down' },
      { emoji: '☝️', keywords: 'index pointing up' },
      { emoji: '👍', keywords: 'thumbs up like good yes' },
      { emoji: '👎', keywords: 'thumbs down dislike bad no' },
      { emoji: '✊', keywords: 'raised fist power solidarity' },
      { emoji: '👊', keywords: 'oncoming fist punch bump' },
      { emoji: '🤛', keywords: 'left facing fist bump' },
      { emoji: '🤜', keywords: 'right facing fist bump' },
      { emoji: '👏', keywords: 'clapping hands applause bravo' },
      { emoji: '🙌', keywords: 'raising hands celebration hooray' },
      { emoji: '👐', keywords: 'open hands hug' },
      { emoji: '🤲', keywords: 'palms up together prayer' },
      { emoji: '🤝', keywords: 'handshake agreement deal' },
      { emoji: '🙏', keywords: 'folded hands prayer please thanks' },
      { emoji: '✍️', keywords: 'writing hand' },
      { emoji: '💅', keywords: 'nail polish manicure' },
      { emoji: '🤳', keywords: 'selfie phone camera' },
      { emoji: '💪', keywords: 'flexed biceps strong muscle' },
      { emoji: '🦾', keywords: 'mechanical arm prosthetic robot' },
      { emoji: '🦿', keywords: 'mechanical leg prosthetic' },
      { emoji: '🦵', keywords: 'leg kick' },
      { emoji: '🦶', keywords: 'foot kick' },
      { emoji: '👂', keywords: 'ear listen hear' },
      { emoji: '🦻', keywords: 'ear hearing aid' },
      { emoji: '👃', keywords: 'nose smell' },
      { emoji: '🧠', keywords: 'brain smart think mind' },
      { emoji: '👀', keywords: 'eyes look see watch' },
      { emoji: '👁️', keywords: 'eye look see' },
      { emoji: '👅', keywords: 'tongue taste lick' },
      { emoji: '👄', keywords: 'mouth lips kiss' },
    ],
  },
  {
    name: 'People',
    icon: '👤',
    emojis: [
      { emoji: '👶', keywords: 'baby infant child' },
      { emoji: '🧒', keywords: 'child kid young' },
      { emoji: '👦', keywords: 'boy child young male' },
      { emoji: '👧', keywords: 'girl child young female' },
      { emoji: '🧑', keywords: 'person adult' },
      { emoji: '👱', keywords: 'person blond hair' },
      { emoji: '👨', keywords: 'man adult male' },
      { emoji: '🧔', keywords: 'man beard' },
      { emoji: '👩', keywords: 'woman adult female' },
      { emoji: '🧓', keywords: 'older person elderly' },
      { emoji: '👴', keywords: 'old man elderly grandfather' },
      { emoji: '👵', keywords: 'old woman elderly grandmother' },
      { emoji: '🙍', keywords: 'person frowning sad' },
      { emoji: '🙎', keywords: 'person pouting angry' },
      { emoji: '🙅', keywords: 'person gesturing no' },
      { emoji: '🙆', keywords: 'person gesturing ok yes' },
      { emoji: '💁', keywords: 'person tipping hand info' },
      { emoji: '🙋', keywords: 'person raising hand question' },
      { emoji: '🧏', keywords: 'deaf person sign language' },
      { emoji: '🙇', keywords: 'person bowing respect sorry' },
      { emoji: '🤦', keywords: 'person facepalming frustrated' },
      { emoji: '🤷', keywords: 'person shrugging idk dunno' },
      { emoji: '👮', keywords: 'police officer cop law' },
      { emoji: '🕵️', keywords: 'detective spy sleuth' },
      { emoji: '💂', keywords: 'guard royal british' },
      { emoji: '🥷', keywords: 'ninja stealth warrior' },
      { emoji: '👷', keywords: 'construction worker builder' },
      { emoji: '🤴', keywords: 'prince royal king' },
      { emoji: '👸', keywords: 'princess royal queen' },
      { emoji: '👳', keywords: 'person turban' },
      { emoji: '👲', keywords: 'person skullcap chinese' },
      { emoji: '🧕', keywords: 'woman headscarf hijab' },
      { emoji: '🤵', keywords: 'person tuxedo formal groom' },
      { emoji: '👰', keywords: 'person veil bride wedding' },
      { emoji: '🤰', keywords: 'pregnant woman baby' },
      { emoji: '🤱', keywords: 'breast feeding baby nursing' },
      { emoji: '👼', keywords: 'baby angel cherub' },
      { emoji: '🎅', keywords: 'santa claus christmas' },
      { emoji: '🤶', keywords: 'mrs claus christmas' },
      { emoji: '🦸', keywords: 'superhero hero power' },
      { emoji: '🦹', keywords: 'supervillain villain evil' },
      { emoji: '🧙', keywords: 'mage wizard magic' },
      { emoji: '🧚', keywords: 'fairy magic fantasy' },
      { emoji: '🧛', keywords: 'vampire dracula halloween' },
      { emoji: '🧜', keywords: 'merperson mermaid ocean' },
      { emoji: '🧝', keywords: 'elf fantasy magic' },
      { emoji: '🧞', keywords: 'genie magic lamp wish' },
      { emoji: '🧟', keywords: 'zombie undead halloween' },
      { emoji: '💆', keywords: 'person getting massage spa' },
      { emoji: '💇', keywords: 'person getting haircut salon' },
      { emoji: '🚶', keywords: 'person walking pedestrian' },
      { emoji: '🧍', keywords: 'person standing' },
      { emoji: '🧎', keywords: 'person kneeling' },
      { emoji: '🏃', keywords: 'person running jogging exercise' },
      { emoji: '💃', keywords: 'woman dancing salsa' },
      { emoji: '🕺', keywords: 'man dancing disco' },
      { emoji: '👯', keywords: 'people bunny ears party' },
      { emoji: '🧖', keywords: 'person steamy room sauna spa' },
      { emoji: '🧗', keywords: 'person climbing rock' },
      { emoji: '🤺', keywords: 'person fencing sword' },
      { emoji: '🏇', keywords: 'horse racing jockey' },
      { emoji: '⛷️', keywords: 'skier skiing snow winter' },
      { emoji: '🏂', keywords: 'snowboarder snow winter' },
      { emoji: '🏌️', keywords: 'person golfing golf' },
      { emoji: '🏄', keywords: 'person surfing wave ocean' },
      { emoji: '🚣', keywords: 'person rowing boat' },
      { emoji: '🏊', keywords: 'person swimming pool' },
      { emoji: '⛹️', keywords: 'person bouncing ball basketball' },
      { emoji: '🏋️', keywords: 'person lifting weights gym' },
      { emoji: '🚴', keywords: 'person biking cycling' },
      { emoji: '🚵', keywords: 'person mountain biking' },
      { emoji: '🤸', keywords: 'person cartwheeling gymnastics' },
      { emoji: '🤼', keywords: 'people wrestling sport' },
      { emoji: '🤽', keywords: 'person playing water polo' },
      { emoji: '🤾', keywords: 'person playing handball' },
      { emoji: '🤹', keywords: 'person juggling circus' },
      { emoji: '🧘', keywords: 'person lotus position yoga meditation' },
      { emoji: '🛀', keywords: 'person taking bath relax' },
      { emoji: '🛌', keywords: 'person in bed sleeping' },
      { emoji: '👭', keywords: 'women holding hands friends' },
      { emoji: '👫', keywords: 'woman man holding hands couple' },
      { emoji: '👬', keywords: 'men holding hands friends' },
      { emoji: '💏', keywords: 'kiss couple love' },
      { emoji: '💑', keywords: 'couple heart love' },
      { emoji: '👪', keywords: 'family parents children' },
      { emoji: '👨‍👩‍👦', keywords: 'family man woman boy' },
      { emoji: '👨‍👩‍👧', keywords: 'family man woman girl' },
      { emoji: '👨‍👩‍👧‍👦', keywords: 'family man woman girl boy' },
      { emoji: '👨‍👩‍👦‍👦', keywords: 'family man woman boy boy' },
      { emoji: '👨‍👩‍👧‍👧', keywords: 'family man woman girl girl' },
      { emoji: '👤', keywords: 'bust silhouette person user profile' },
      { emoji: '👥', keywords: 'busts silhouette people users group' },
      { emoji: '🫂', keywords: 'people hugging hug embrace' },
      { emoji: '👣', keywords: 'footprints feet tracks' },
    ],
  },
  {
    name: 'Animals',
    icon: '🐶',
    emojis: [
      { emoji: '🐵', keywords: 'monkey face animal' },
      { emoji: '🐒', keywords: 'monkey animal primate' },
      { emoji: '🦍', keywords: 'gorilla animal ape' },
      { emoji: '🦧', keywords: 'orangutan animal ape' },
      { emoji: '🐶', keywords: 'dog face puppy pet' },
      { emoji: '🐕', keywords: 'dog pet animal' },
      { emoji: '🦮', keywords: 'guide dog service' },
      { emoji: '🐕‍🦺', keywords: 'service dog' },
      { emoji: '🐩', keywords: 'poodle dog pet' },
      { emoji: '🐺', keywords: 'wolf animal howl' },
      { emoji: '🦊', keywords: 'fox face animal' },
      { emoji: '🦝', keywords: 'raccoon animal' },
      { emoji: '🐱', keywords: 'cat face pet kitten' },
      { emoji: '🐈', keywords: 'cat pet animal' },
      { emoji: '🐈‍⬛', keywords: 'black cat' },
      { emoji: '🦁', keywords: 'lion face king' },
      { emoji: '🐯', keywords: 'tiger face animal' },
      { emoji: '🐅', keywords: 'tiger animal stripes' },
      { emoji: '🐆', keywords: 'leopard animal spots' },
      { emoji: '🐴', keywords: 'horse face animal' },
      { emoji: '🐎', keywords: 'horse racing animal' },
      { emoji: '🦄', keywords: 'unicorn magic fantasy' },
      { emoji: '🦓', keywords: 'zebra animal stripes' },
      { emoji: '🦌', keywords: 'deer animal antlers' },
      { emoji: '🦬', keywords: 'bison buffalo animal' },
      { emoji: '🐮', keywords: 'cow face animal' },
      { emoji: '🐂', keywords: 'ox animal bull' },
      { emoji: '🐃', keywords: 'water buffalo animal' },
      { emoji: '🐄', keywords: 'cow animal farm' },
      { emoji: '🐷', keywords: 'pig face animal' },
      { emoji: '🐖', keywords: 'pig animal farm' },
      { emoji: '🐗', keywords: 'boar animal wild pig' },
      { emoji: '🐽', keywords: 'pig nose snout' },
      { emoji: '🐏', keywords: 'ram sheep animal' },
      { emoji: '🐑', keywords: 'ewe sheep animal wool' },
      { emoji: '🐐', keywords: 'goat animal' },
      { emoji: '🐪', keywords: 'camel dromedary desert' },
      { emoji: '🐫', keywords: 'two hump camel bactrian' },
      { emoji: '🦙', keywords: 'llama animal alpaca' },
      { emoji: '🦒', keywords: 'giraffe animal tall' },
      { emoji: '🐘', keywords: 'elephant animal trunk' },
      { emoji: '🦣', keywords: 'mammoth extinct elephant' },
      { emoji: '🦏', keywords: 'rhinoceros animal horn' },
      { emoji: '🦛', keywords: 'hippopotamus animal hippo' },
      { emoji: '🐭', keywords: 'mouse face animal' },
      { emoji: '🐁', keywords: 'mouse animal rodent' },
      { emoji: '🐀', keywords: 'rat animal rodent' },
      { emoji: '🐹', keywords: 'hamster face pet' },
      { emoji: '🐰', keywords: 'rabbit face bunny' },
      { emoji: '🐇', keywords: 'rabbit bunny animal' },
      { emoji: '🐿️', keywords: 'chipmunk squirrel animal' },
      { emoji: '🦫', keywords: 'beaver animal dam' },
      { emoji: '🦔', keywords: 'hedgehog animal spines' },
      { emoji: '🦇', keywords: 'bat animal night' },
      { emoji: '🐻', keywords: 'bear face animal' },
      { emoji: '🐻‍❄️', keywords: 'polar bear arctic' },
      { emoji: '🐨', keywords: 'koala animal australia' },
      { emoji: '🐼', keywords: 'panda face animal' },
      { emoji: '🦥', keywords: 'sloth animal slow' },
      { emoji: '🦦', keywords: 'otter animal water' },
      { emoji: '🦨', keywords: 'skunk animal smell' },
      { emoji: '🦘', keywords: 'kangaroo australia animal' },
      { emoji: '🦡', keywords: 'badger animal' },
      { emoji: '🐾', keywords: 'paw prints animal feet' },
      { emoji: '🦃', keywords: 'turkey bird thanksgiving' },
      { emoji: '🐔', keywords: 'chicken bird farm' },
      { emoji: '🐓', keywords: 'rooster bird cock' },
      { emoji: '🐣', keywords: 'hatching chick baby bird' },
      { emoji: '🐤', keywords: 'baby chick bird' },
      { emoji: '🐥', keywords: 'front facing baby chick' },
      { emoji: '🐦', keywords: 'bird animal' },
      { emoji: '🐧', keywords: 'penguin bird cold' },
      { emoji: '🕊️', keywords: 'dove peace bird' },
      { emoji: '🦅', keywords: 'eagle bird america' },
      { emoji: '🦆', keywords: 'duck bird quack' },
      { emoji: '🦢', keywords: 'swan bird elegant' },
      { emoji: '🦉', keywords: 'owl bird night wise' },
      { emoji: '🦤', keywords: 'dodo bird extinct' },
      { emoji: '🪶', keywords: 'feather bird light' },
      { emoji: '🦩', keywords: 'flamingo bird pink' },
      { emoji: '🦚', keywords: 'peacock bird colorful' },
      { emoji: '🦜', keywords: 'parrot bird colorful talk' },
      { emoji: '🐸', keywords: 'frog face animal' },
      { emoji: '🐊', keywords: 'crocodile alligator animal' },
      { emoji: '🐢', keywords: 'turtle tortoise animal slow' },
      { emoji: '🦎', keywords: 'lizard reptile animal' },
      { emoji: '🐍', keywords: 'snake reptile animal' },
      { emoji: '🐲', keywords: 'dragon face fantasy' },
      { emoji: '🐉', keywords: 'dragon fantasy fire' },
      { emoji: '🦕', keywords: 'sauropod dinosaur' },
      { emoji: '🦖', keywords: 't-rex dinosaur' },
      { emoji: '🐳', keywords: 'spouting whale ocean' },
      { emoji: '🐋', keywords: 'whale ocean mammal' },
      { emoji: '🐬', keywords: 'dolphin ocean mammal' },
      { emoji: '🦭', keywords: 'seal ocean animal' },
      { emoji: '🐟', keywords: 'fish ocean animal' },
      { emoji: '🐠', keywords: 'tropical fish colorful' },
      { emoji: '🐡', keywords: 'blowfish puffer fish' },
      { emoji: '🦈', keywords: 'shark ocean predator' },
      { emoji: '🐙', keywords: 'octopus ocean tentacles' },
      { emoji: '🐚', keywords: 'spiral shell beach' },
      { emoji: '🐌', keywords: 'snail slow animal' },
      { emoji: '🦋', keywords: 'butterfly insect pretty' },
      { emoji: '🐛', keywords: 'bug caterpillar insect' },
      { emoji: '🐜', keywords: 'ant insect small' },
      { emoji: '🐝', keywords: 'honeybee bee insect' },
      { emoji: '🪲', keywords: 'beetle bug insect' },
      { emoji: '🐞', keywords: 'lady beetle ladybug' },
      { emoji: '🦗', keywords: 'cricket insect chirp' },
      { emoji: '🪳', keywords: 'cockroach bug insect' },
      { emoji: '🕷️', keywords: 'spider web insect' },
      { emoji: '🕸️', keywords: 'spider web' },
      { emoji: '🦂', keywords: 'scorpion arachnid sting' },
      { emoji: '🦟', keywords: 'mosquito bug bite' },
      { emoji: '🪰', keywords: 'fly bug insect' },
      { emoji: '🪱', keywords: 'worm earth crawl' },
      { emoji: '🦠', keywords: 'microbe germ bacteria virus' },
    ],
  },
  {
    name: 'Nature',
    icon: '🌸',
    emojis: [
      { emoji: '💐', keywords: 'bouquet flowers' },
      { emoji: '🌸', keywords: 'cherry blossom flower spring' },
      { emoji: '💮', keywords: 'white flower' },
      { emoji: '🏵️', keywords: 'rosette flower' },
      { emoji: '🌹', keywords: 'rose flower love red' },
      { emoji: '🥀', keywords: 'wilted flower dead' },
      { emoji: '🌺', keywords: 'hibiscus flower tropical' },
      { emoji: '🌻', keywords: 'sunflower yellow' },
      { emoji: '🌼', keywords: 'blossom flower' },
      { emoji: '🌷', keywords: 'tulip flower spring' },
      { emoji: '🌱', keywords: 'seedling plant grow' },
      { emoji: '🪴', keywords: 'potted plant houseplant' },
      { emoji: '🌲', keywords: 'evergreen tree pine' },
      { emoji: '🌳', keywords: 'deciduous tree' },
      { emoji: '🌴', keywords: 'palm tree tropical beach' },
      { emoji: '🌵', keywords: 'cactus desert plant' },
      { emoji: '🌾', keywords: 'sheaf rice grain wheat' },
      { emoji: '🌿', keywords: 'herb plant leaf' },
      { emoji: '☘️', keywords: 'shamrock clover irish' },
      { emoji: '🍀', keywords: 'four leaf clover lucky' },
      { emoji: '🍁', keywords: 'maple leaf fall autumn' },
      { emoji: '🍂', keywords: 'fallen leaf autumn' },
      { emoji: '🍃', keywords: 'leaf fluttering wind' },
      { emoji: '🌍', keywords: 'globe europe africa earth world' },
      { emoji: '🌎', keywords: 'globe americas earth world' },
      { emoji: '🌏', keywords: 'globe asia australia earth world' },
      { emoji: '🌐', keywords: 'globe meridians earth internet' },
      { emoji: '🌑', keywords: 'new moon dark' },
      { emoji: '🌒', keywords: 'waxing crescent moon' },
      { emoji: '🌓', keywords: 'first quarter moon' },
      { emoji: '🌔', keywords: 'waxing gibbous moon' },
      { emoji: '🌕', keywords: 'full moon night' },
      { emoji: '🌖', keywords: 'waning gibbous moon' },
      { emoji: '🌗', keywords: 'last quarter moon' },
      { emoji: '🌘', keywords: 'waning crescent moon' },
      { emoji: '🌙', keywords: 'crescent moon night' },
      { emoji: '🌚', keywords: 'new moon face' },
      { emoji: '🌛', keywords: 'first quarter moon face' },
      { emoji: '🌜', keywords: 'last quarter moon face' },
      { emoji: '🌡️', keywords: 'thermometer temperature' },
      { emoji: '☀️', keywords: 'sun sunny weather hot' },
      { emoji: '🌝', keywords: 'full moon face' },
      { emoji: '🌞', keywords: 'sun face happy' },
      { emoji: '🪐', keywords: 'ringed planet saturn' },
      { emoji: '⭐', keywords: 'star night sky' },
      { emoji: '🌟', keywords: 'glowing star sparkle' },
      { emoji: '🌠', keywords: 'shooting star wish' },
      { emoji: '🌌', keywords: 'milky way galaxy stars' },
      { emoji: '☁️', keywords: 'cloud weather' },
      { emoji: '⛅', keywords: 'sun behind cloud weather' },
      { emoji: '⛈️', keywords: 'cloud lightning rain storm' },
      { emoji: '🌤️', keywords: 'sun behind small cloud' },
      { emoji: '🌥️', keywords: 'sun behind large cloud' },
      { emoji: '🌦️', keywords: 'sun behind rain cloud' },
      { emoji: '🌧️', keywords: 'cloud rain weather' },
      { emoji: '🌨️', keywords: 'cloud snow weather' },
      { emoji: '🌩️', keywords: 'cloud lightning' },
      { emoji: '🌪️', keywords: 'tornado weather storm' },
      { emoji: '🌫️', keywords: 'fog weather' },
      { emoji: '🌬️', keywords: 'wind face blowing' },
      { emoji: '🌀', keywords: 'cyclone hurricane spiral' },
      { emoji: '🌈', keywords: 'rainbow weather colorful' },
      { emoji: '🌂', keywords: 'closed umbrella rain' },
      { emoji: '☂️', keywords: 'umbrella rain' },
      { emoji: '☔', keywords: 'umbrella rain drops' },
      { emoji: '⛱️', keywords: 'umbrella ground beach' },
      { emoji: '⚡', keywords: 'high voltage lightning electric' },
      { emoji: '❄️', keywords: 'snowflake cold winter' },
      { emoji: '☃️', keywords: 'snowman winter cold' },
      { emoji: '⛄', keywords: 'snowman without snow winter' },
      { emoji: '☄️', keywords: 'comet space meteor' },
      { emoji: '🔥', keywords: 'fire hot flame lit' },
      { emoji: '💧', keywords: 'droplet water tear' },
      { emoji: '🌊', keywords: 'water wave ocean surf' },
    ],
  },
  {
    name: 'Food',
    icon: '🍔',
    emojis: [
      { emoji: '🍇', keywords: 'grapes fruit purple' },
      { emoji: '🍈', keywords: 'melon fruit' },
      { emoji: '🍉', keywords: 'watermelon fruit summer' },
      { emoji: '🍊', keywords: 'tangerine orange fruit' },
      { emoji: '🍋', keywords: 'lemon fruit sour yellow' },
      { emoji: '🍌', keywords: 'banana fruit yellow' },
      { emoji: '🍍', keywords: 'pineapple fruit tropical' },
      { emoji: '🥭', keywords: 'mango fruit tropical' },
      { emoji: '🍎', keywords: 'red apple fruit' },
      { emoji: '🍏', keywords: 'green apple fruit' },
      { emoji: '🍐', keywords: 'pear fruit' },
      { emoji: '🍑', keywords: 'peach fruit' },
      { emoji: '🍒', keywords: 'cherries fruit red' },
      { emoji: '🍓', keywords: 'strawberry fruit red' },
      { emoji: '🫐', keywords: 'blueberries fruit blue' },
      { emoji: '🥝', keywords: 'kiwi fruit green' },
      { emoji: '🍅', keywords: 'tomato vegetable red' },
      { emoji: '🫒', keywords: 'olive green' },
      { emoji: '🥥', keywords: 'coconut tropical' },
      { emoji: '🥑', keywords: 'avocado fruit green' },
      { emoji: '🍆', keywords: 'eggplant vegetable purple' },
      { emoji: '🥔', keywords: 'potato vegetable' },
      { emoji: '🥕', keywords: 'carrot vegetable orange' },
      { emoji: '🌽', keywords: 'ear corn vegetable' },
      { emoji: '🌶️', keywords: 'hot pepper spicy chili' },
      { emoji: '🫑', keywords: 'bell pepper vegetable' },
      { emoji: '🥒', keywords: 'cucumber vegetable green' },
      { emoji: '🥬', keywords: 'leafy green vegetable' },
      { emoji: '🥦', keywords: 'broccoli vegetable green' },
      { emoji: '🧄', keywords: 'garlic vegetable' },
      { emoji: '🧅', keywords: 'onion vegetable' },
      { emoji: '🍄', keywords: 'mushroom fungus' },
      { emoji: '🥜', keywords: 'peanuts nuts' },
      { emoji: '🌰', keywords: 'chestnut nut' },
      { emoji: '🍞', keywords: 'bread loaf toast' },
      { emoji: '🥐', keywords: 'croissant bread french' },
      { emoji: '🥖', keywords: 'baguette bread french' },
      { emoji: '🫓', keywords: 'flatbread pita naan' },
      { emoji: '🥨', keywords: 'pretzel snack' },
      { emoji: '🥯', keywords: 'bagel bread breakfast' },
      { emoji: '🥞', keywords: 'pancakes breakfast' },
      { emoji: '🧇', keywords: 'waffle breakfast' },
      { emoji: '🧀', keywords: 'cheese wedge' },
      { emoji: '🍖', keywords: 'meat bone' },
      { emoji: '🍗', keywords: 'poultry leg chicken' },
      { emoji: '🥩', keywords: 'cut meat steak' },
      { emoji: '🥓', keywords: 'bacon meat breakfast' },
      { emoji: '🍔', keywords: 'hamburger burger fast food' },
      { emoji: '🍟', keywords: 'french fries fast food' },
      { emoji: '🍕', keywords: 'pizza slice fast food' },
      { emoji: '🌭', keywords: 'hot dog fast food' },
      { emoji: '🥪', keywords: 'sandwich lunch' },
      { emoji: '🌮', keywords: 'taco mexican food' },
      { emoji: '🌯', keywords: 'burrito mexican wrap' },
      { emoji: '🫔', keywords: 'tamale mexican food' },
      { emoji: '🥙', keywords: 'stuffed flatbread pita falafel' },
      { emoji: '🧆', keywords: 'falafel middle eastern' },
      { emoji: '🥚', keywords: 'egg breakfast' },
      { emoji: '🍳', keywords: 'cooking egg fried' },
      { emoji: '🥘', keywords: 'shallow pan food paella' },
      { emoji: '🍲', keywords: 'pot food stew soup' },
      { emoji: '🫕', keywords: 'fondue cheese' },
      { emoji: '🥣', keywords: 'bowl spoon cereal' },
      { emoji: '🥗', keywords: 'green salad healthy' },
      { emoji: '🍿', keywords: 'popcorn movie snack' },
      { emoji: '🧈', keywords: 'butter dairy' },
      { emoji: '🧂', keywords: 'salt seasoning' },
      { emoji: '🥫', keywords: 'canned food' },
      { emoji: '🍱', keywords: 'bento box japanese' },
      { emoji: '🍘', keywords: 'rice cracker japanese' },
      { emoji: '🍙', keywords: 'rice ball onigiri' },
      { emoji: '🍚', keywords: 'cooked rice' },
      { emoji: '🍛', keywords: 'curry rice indian' },
      { emoji: '🍜', keywords: 'steaming bowl noodles ramen' },
      { emoji: '🍝', keywords: 'spaghetti pasta italian' },
      { emoji: '🍠', keywords: 'roasted sweet potato' },
      { emoji: '🍢', keywords: 'oden japanese skewer' },
      { emoji: '🍣', keywords: 'sushi japanese fish' },
      { emoji: '🍤', keywords: 'fried shrimp tempura' },
      { emoji: '🍥', keywords: 'fish cake swirl narutomaki' },
      { emoji: '🥮', keywords: 'moon cake chinese' },
      { emoji: '🍡', keywords: 'dango japanese dessert' },
      { emoji: '🥟', keywords: 'dumpling gyoza chinese' },
      { emoji: '🥠', keywords: 'fortune cookie chinese' },
      { emoji: '🥡', keywords: 'takeout box chinese' },
      { emoji: '🦀', keywords: 'crab seafood' },
      { emoji: '🦞', keywords: 'lobster seafood' },
      { emoji: '🦐', keywords: 'shrimp prawn seafood' },
      { emoji: '🦑', keywords: 'squid seafood' },
      { emoji: '🦪', keywords: 'oyster seafood shell' },
      { emoji: '🍦', keywords: 'soft ice cream dessert' },
      { emoji: '🍧', keywords: 'shaved ice dessert' },
      { emoji: '🍨', keywords: 'ice cream dessert' },
      { emoji: '🍩', keywords: 'doughnut donut dessert' },
      { emoji: '🍪', keywords: 'cookie dessert' },
      { emoji: '🎂', keywords: 'birthday cake celebration' },
      { emoji: '🍰', keywords: 'shortcake dessert slice' },
      { emoji: '🧁', keywords: 'cupcake dessert' },
      { emoji: '🥧', keywords: 'pie dessert' },
      { emoji: '🍫', keywords: 'chocolate bar candy' },
      { emoji: '🍬', keywords: 'candy sweet' },
      { emoji: '🍭', keywords: 'lollipop candy sweet' },
      { emoji: '🍮', keywords: 'custard pudding dessert' },
      { emoji: '🍯', keywords: 'honey pot sweet' },
      { emoji: '🍼', keywords: 'baby bottle milk' },
      { emoji: '🥛', keywords: 'glass milk' },
      { emoji: '☕', keywords: 'hot beverage coffee tea' },
      { emoji: '🫖', keywords: 'teapot tea' },
      { emoji: '🍵', keywords: 'teacup tea green' },
      { emoji: '🍶', keywords: 'sake japanese alcohol' },
      { emoji: '🍾', keywords: 'bottle popping cork champagne' },
      { emoji: '🍷', keywords: 'wine glass red' },
      { emoji: '🍸', keywords: 'cocktail glass martini' },
      { emoji: '🍹', keywords: 'tropical drink cocktail' },
      { emoji: '🍺', keywords: 'beer mug drink' },
      { emoji: '🍻', keywords: 'clinking beer mugs cheers' },
      { emoji: '🥂', keywords: 'clinking glasses toast champagne' },
      { emoji: '🥃', keywords: 'tumbler glass whiskey' },
      { emoji: '🥤', keywords: 'cup straw soda' },
      { emoji: '🧋', keywords: 'bubble tea boba' },
      { emoji: '🧃', keywords: 'beverage box juice' },
      { emoji: '🧉', keywords: 'mate drink' },
      { emoji: '🧊', keywords: 'ice cube cold' },
      { emoji: '🥢', keywords: 'chopsticks asian' },
      { emoji: '🍽️', keywords: 'fork knife plate dining' },
      { emoji: '🍴', keywords: 'fork knife cutlery' },
      { emoji: '🥄', keywords: 'spoon' },
      { emoji: '🔪', keywords: 'kitchen knife chef' },
      { emoji: '🏺', keywords: 'amphora jar vase' },
    ],
  },
  {
    name: 'Activities',
    icon: '⚽',
    emojis: [
      { emoji: '🎃', keywords: 'jack o lantern halloween pumpkin' },
      { emoji: '🎄', keywords: 'christmas tree holiday' },
      { emoji: '🎆', keywords: 'fireworks celebration' },
      { emoji: '🎇', keywords: 'sparkler fireworks celebration' },
      { emoji: '🧨', keywords: 'firecracker explosive' },
      { emoji: '✨', keywords: 'sparkles magic stars' },
      { emoji: '🎈', keywords: 'balloon party celebration' },
      { emoji: '🎉', keywords: 'party popper celebration confetti' },
      { emoji: '🎊', keywords: 'confetti ball celebration' },
      { emoji: '🎋', keywords: 'tanabata tree japanese' },
      { emoji: '🎍', keywords: 'pine decoration japanese' },
      { emoji: '🎎', keywords: 'japanese dolls hinamatsuri' },
      { emoji: '🎏', keywords: 'carp streamer japanese' },
      { emoji: '🎐', keywords: 'wind chime japanese' },
      { emoji: '🎑', keywords: 'moon viewing ceremony' },
      { emoji: '🧧', keywords: 'red envelope chinese' },
      { emoji: '🎀', keywords: 'ribbon bow gift' },
      { emoji: '🎁', keywords: 'wrapped gift present birthday' },
      { emoji: '🎗️', keywords: 'reminder ribbon awareness' },
      { emoji: '🎟️', keywords: 'admission tickets' },
      { emoji: '🎫', keywords: 'ticket admission' },
      { emoji: '🎖️', keywords: 'military medal award' },
      { emoji: '🏆', keywords: 'trophy winner champion' },
      { emoji: '🏅', keywords: 'sports medal winner' },
      { emoji: '🥇', keywords: 'first place medal gold' },
      { emoji: '🥈', keywords: 'second place medal silver' },
      { emoji: '🥉', keywords: 'third place medal bronze' },
      { emoji: '⚽', keywords: 'soccer ball football sport' },
      { emoji: '⚾', keywords: 'baseball sport' },
      { emoji: '🥎', keywords: 'softball sport' },
      { emoji: '🏀', keywords: 'basketball sport' },
      { emoji: '🏐', keywords: 'volleyball sport' },
      { emoji: '🏈', keywords: 'american football sport' },
      { emoji: '🏉', keywords: 'rugby football sport' },
      { emoji: '🎾', keywords: 'tennis ball sport' },
      { emoji: '🥏', keywords: 'flying disc frisbee' },
      { emoji: '🎳', keywords: 'bowling sport' },
      { emoji: '🏏', keywords: 'cricket game sport' },
      { emoji: '🏑', keywords: 'field hockey sport' },
      { emoji: '🏒', keywords: 'ice hockey sport' },
      { emoji: '🥍', keywords: 'lacrosse sport' },
      { emoji: '🏓', keywords: 'ping pong table tennis' },
      { emoji: '🏸', keywords: 'badminton sport' },
      { emoji: '🥊', keywords: 'boxing glove sport' },
      { emoji: '🥋', keywords: 'martial arts uniform karate' },
      { emoji: '🥅', keywords: 'goal net sport' },
      { emoji: '⛳', keywords: 'flag hole golf' },
      { emoji: '⛸️', keywords: 'ice skate skating' },
      { emoji: '🎣', keywords: 'fishing pole' },
      { emoji: '🤿', keywords: 'diving mask snorkel' },
      { emoji: '🎽', keywords: 'running shirt sport' },
      { emoji: '🎿', keywords: 'skis skiing winter' },
      { emoji: '🛷', keywords: 'sled sledge winter' },
      { emoji: '🥌', keywords: 'curling stone sport' },
      { emoji: '🎯', keywords: 'direct hit target bullseye dart' },
      { emoji: '🪀', keywords: 'yo yo toy' },
      { emoji: '🪁', keywords: 'kite flying' },
      { emoji: '🎱', keywords: 'pool 8 ball billiards' },
      { emoji: '🔮', keywords: 'crystal ball fortune magic' },
      { emoji: '🪄', keywords: 'magic wand wizard' },
      { emoji: '🧿', keywords: 'nazar amulet evil eye' },
      { emoji: '🎮', keywords: 'video game controller' },
      { emoji: '🕹️', keywords: 'joystick game arcade' },
      { emoji: '🎰', keywords: 'slot machine casino gambling' },
      { emoji: '🎲', keywords: 'game die dice' },
      { emoji: '🧩', keywords: 'puzzle piece jigsaw' },
      { emoji: '🧸', keywords: 'teddy bear toy' },
      { emoji: '🪆', keywords: 'nesting dolls matryoshka' },
      { emoji: '♠️', keywords: 'spade suit cards' },
      { emoji: '♥️', keywords: 'heart suit cards' },
      { emoji: '♦️', keywords: 'diamond suit cards' },
      { emoji: '♣️', keywords: 'club suit cards' },
      { emoji: '♟️', keywords: 'chess pawn' },
      { emoji: '🃏', keywords: 'joker card' },
      { emoji: '🀄', keywords: 'mahjong red dragon' },
      { emoji: '🎴', keywords: 'flower playing cards' },
      { emoji: '🎭', keywords: 'performing arts theater drama' },
      { emoji: '🖼️', keywords: 'framed picture art' },
      { emoji: '🎨', keywords: 'artist palette painting art' },
      { emoji: '🧵', keywords: 'thread sewing' },
      { emoji: '🪡', keywords: 'sewing needle' },
      { emoji: '🧶', keywords: 'yarn knitting' },
      { emoji: '🪢', keywords: 'knot rope' },
    ],
  },
  {
    name: 'Travel',
    icon: '🚗',
    emojis: [
      { emoji: '🚗', keywords: 'automobile car vehicle' },
      { emoji: '🚕', keywords: 'taxi cab car' },
      { emoji: '🚙', keywords: 'sport utility vehicle suv' },
      { emoji: '🚌', keywords: 'bus public transport' },
      { emoji: '🚎', keywords: 'trolleybus electric' },
      { emoji: '🏎️', keywords: 'racing car formula' },
      { emoji: '🚓', keywords: 'police car law' },
      { emoji: '🚑', keywords: 'ambulance emergency medical' },
      { emoji: '🚒', keywords: 'fire engine truck' },
      { emoji: '🚐', keywords: 'minibus van' },
      { emoji: '🛻', keywords: 'pickup truck' },
      { emoji: '🚚', keywords: 'delivery truck' },
      { emoji: '🚛', keywords: 'articulated lorry semi truck' },
      { emoji: '🚜', keywords: 'tractor farm' },
      { emoji: '🦯', keywords: 'white cane blind' },
      { emoji: '🦽', keywords: 'manual wheelchair' },
      { emoji: '🦼', keywords: 'motorized wheelchair' },
      { emoji: '🛴', keywords: 'kick scooter' },
      { emoji: '🚲', keywords: 'bicycle bike cycling' },
      { emoji: '🛵', keywords: 'motor scooter moped' },
      { emoji: '🏍️', keywords: 'motorcycle racing' },
      { emoji: '🛺', keywords: 'auto rickshaw tuk tuk' },
      { emoji: '🚨', keywords: 'police car light emergency' },
      { emoji: '🚔', keywords: 'oncoming police car' },
      { emoji: '🚍', keywords: 'oncoming bus' },
      { emoji: '🚘', keywords: 'oncoming automobile car' },
      { emoji: '🚖', keywords: 'oncoming taxi' },
      { emoji: '🚡', keywords: 'aerial tramway cable car' },
      { emoji: '🚠', keywords: 'mountain cableway' },
      { emoji: '🚟', keywords: 'suspension railway' },
      { emoji: '🚃', keywords: 'railway car train' },
      { emoji: '🚋', keywords: 'tram car streetcar' },
      { emoji: '🚞', keywords: 'mountain railway' },
      { emoji: '🚝', keywords: 'monorail train' },
      { emoji: '🚄', keywords: 'high speed train bullet' },
      { emoji: '🚅', keywords: 'bullet train shinkansen' },
      { emoji: '🚈', keywords: 'light rail train' },
      { emoji: '🚂', keywords: 'locomotive steam train' },
      { emoji: '🚆', keywords: 'train' },
      { emoji: '🚇', keywords: 'metro subway underground' },
      { emoji: '🚊', keywords: 'tram streetcar' },
      { emoji: '🚉', keywords: 'station train' },
      { emoji: '✈️', keywords: 'airplane plane travel flight' },
      { emoji: '🛫', keywords: 'airplane departure takeoff' },
      { emoji: '🛬', keywords: 'airplane arrival landing' },
      { emoji: '🛩️', keywords: 'small airplane plane' },
      { emoji: '💺', keywords: 'seat airplane' },
      { emoji: '🛰️', keywords: 'satellite space' },
      { emoji: '🚀', keywords: 'rocket space launch' },
      { emoji: '🛸', keywords: 'flying saucer ufo alien' },
      { emoji: '🚁', keywords: 'helicopter' },
      { emoji: '🛶', keywords: 'canoe kayak' },
      { emoji: '⛵', keywords: 'sailboat boat sailing' },
      { emoji: '🚤', keywords: 'speedboat motorboat' },
      { emoji: '🛥️', keywords: 'motor boat yacht' },
      { emoji: '🛳️', keywords: 'passenger ship cruise' },
      { emoji: '⛴️', keywords: 'ferry boat' },
      { emoji: '🚢', keywords: 'ship boat' },
      { emoji: '⚓', keywords: 'anchor ship boat' },
      { emoji: '🪝', keywords: 'hook fishing' },
      { emoji: '⛽', keywords: 'fuel pump gas station' },
      { emoji: '🚧', keywords: 'construction barrier' },
      { emoji: '🚦', keywords: 'vertical traffic light' },
      { emoji: '🚥', keywords: 'horizontal traffic light' },
      { emoji: '🚏', keywords: 'bus stop' },
      { emoji: '🗺️', keywords: 'world map travel' },
      { emoji: '🗿', keywords: 'moai statue easter island' },
      { emoji: '🗽', keywords: 'statue liberty new york' },
      { emoji: '🗼', keywords: 'tokyo tower japan' },
      { emoji: '🏰', keywords: 'castle european' },
      { emoji: '🏯', keywords: 'japanese castle' },
      { emoji: '🏟️', keywords: 'stadium sports' },
      { emoji: '🎡', keywords: 'ferris wheel carnival' },
      { emoji: '🎢', keywords: 'roller coaster amusement' },
      { emoji: '🎠', keywords: 'carousel horse merry go round' },
      { emoji: '⛲', keywords: 'fountain water' },
      { emoji: '⛱️', keywords: 'umbrella ground beach' },
      { emoji: '🏖️', keywords: 'beach umbrella vacation' },
      { emoji: '🏝️', keywords: 'desert island tropical' },
      { emoji: '🏜️', keywords: 'desert sand' },
      { emoji: '🌋', keywords: 'volcano eruption' },
      { emoji: '⛰️', keywords: 'mountain' },
      { emoji: '🏔️', keywords: 'snow capped mountain' },
      { emoji: '🗻', keywords: 'mount fuji japan' },
      { emoji: '🏕️', keywords: 'camping tent outdoor' },
      { emoji: '⛺', keywords: 'tent camping' },
      { emoji: '🏠', keywords: 'house home building' },
      { emoji: '🏡', keywords: 'house garden home' },
      { emoji: '🏘️', keywords: 'houses buildings neighborhood' },
      { emoji: '🏚️', keywords: 'derelict house abandoned' },
      { emoji: '🏗️', keywords: 'building construction crane' },
      { emoji: '🏢', keywords: 'office building' },
      { emoji: '🏬', keywords: 'department store shopping' },
      { emoji: '🏣', keywords: 'japanese post office' },
      { emoji: '🏤', keywords: 'post office' },
      { emoji: '🏥', keywords: 'hospital medical' },
      { emoji: '🏦', keywords: 'bank money' },
      { emoji: '🏨', keywords: 'hotel lodging' },
      { emoji: '🏪', keywords: 'convenience store shop' },
      { emoji: '🏫', keywords: 'school building education' },
      { emoji: '🏩', keywords: 'love hotel' },
      { emoji: '💒', keywords: 'wedding chapel church' },
      { emoji: '🏛️', keywords: 'classical building museum' },
      { emoji: '⛪', keywords: 'church christian' },
      { emoji: '🕌', keywords: 'mosque muslim islamic' },
      { emoji: '🕍', keywords: 'synagogue jewish' },
      { emoji: '🛕', keywords: 'hindu temple' },
      { emoji: '🕋', keywords: 'kaaba mecca islam' },
      { emoji: '⛩️', keywords: 'shinto shrine japan' },
      { emoji: '🛤️', keywords: 'railway track train' },
      { emoji: '🛣️', keywords: 'motorway highway road' },
      { emoji: '🗾', keywords: 'map japan' },
      { emoji: '🎑', keywords: 'moon viewing ceremony japan' },
      { emoji: '🏞️', keywords: 'national park nature' },
      { emoji: '🌅', keywords: 'sunrise morning' },
      { emoji: '🌄', keywords: 'sunrise mountains' },
      { emoji: '🌠', keywords: 'shooting star night' },
      { emoji: '🎇', keywords: 'sparkler fireworks' },
      { emoji: '🎆', keywords: 'fireworks celebration' },
      { emoji: '🌇', keywords: 'sunset city' },
      { emoji: '🌆', keywords: 'cityscape dusk evening' },
      { emoji: '🏙️', keywords: 'cityscape skyline' },
      { emoji: '🌃', keywords: 'night stars city' },
      { emoji: '🌌', keywords: 'milky way galaxy stars' },
      { emoji: '🌉', keywords: 'bridge night' },
      { emoji: '🌁', keywords: 'foggy city' },
    ],
  },
  {
    name: 'Objects',
    icon: '💡',
    emojis: [
      { emoji: '⌚', keywords: 'watch time wrist' },
      { emoji: '📱', keywords: 'mobile phone cell smartphone' },
      { emoji: '📲', keywords: 'mobile phone arrow call' },
      { emoji: '💻', keywords: 'laptop computer' },
      { emoji: '⌨️', keywords: 'keyboard type' },
      { emoji: '🖥️', keywords: 'desktop computer monitor' },
      { emoji: '🖨️', keywords: 'printer print' },
      { emoji: '🖱️', keywords: 'computer mouse click' },
      { emoji: '🖲️', keywords: 'trackball' },
      { emoji: '💽', keywords: 'computer disk minidisc' },
      { emoji: '💾', keywords: 'floppy disk save' },
      { emoji: '💿', keywords: 'optical disk cd' },
      { emoji: '📀', keywords: 'dvd disc' },
      { emoji: '🧮', keywords: 'abacus calculate' },
      { emoji: '🎥', keywords: 'movie camera film' },
      { emoji: '🎞️', keywords: 'film frames movie' },
      { emoji: '📽️', keywords: 'film projector movie' },
      { emoji: '🎬', keywords: 'clapper board movie action' },
      { emoji: '📺', keywords: 'television tv' },
      { emoji: '📷', keywords: 'camera photo' },
      { emoji: '📸', keywords: 'camera flash photo' },
      { emoji: '📹', keywords: 'video camera camcorder' },
      { emoji: '📼', keywords: 'videocassette vhs tape' },
      { emoji: '🔍', keywords: 'magnifying glass search left' },
      { emoji: '🔎', keywords: 'magnifying glass search right' },
      { emoji: '🕯️', keywords: 'candle light' },
      { emoji: '💡', keywords: 'light bulb idea' },
      { emoji: '🔦', keywords: 'flashlight torch' },
      { emoji: '🏮', keywords: 'red paper lantern' },
      { emoji: '🪔', keywords: 'diya lamp oil' },
      { emoji: '📔', keywords: 'notebook decorative cover' },
      { emoji: '📕', keywords: 'closed book red' },
      { emoji: '📖', keywords: 'open book reading' },
      { emoji: '📗', keywords: 'green book' },
      { emoji: '📘', keywords: 'blue book' },
      { emoji: '📙', keywords: 'orange book' },
      { emoji: '📚', keywords: 'books reading library' },
      { emoji: '📓', keywords: 'notebook' },
      { emoji: '📒', keywords: 'ledger notebook' },
      { emoji: '📃', keywords: 'page curl document' },
      { emoji: '📜', keywords: 'scroll paper document' },
      { emoji: '📄', keywords: 'page facing up document' },
      { emoji: '📰', keywords: 'newspaper news' },
      { emoji: '🗞️', keywords: 'rolled newspaper' },
      { emoji: '📑', keywords: 'bookmark tabs' },
      { emoji: '🔖', keywords: 'bookmark' },
      { emoji: '🏷️', keywords: 'label tag price' },
      { emoji: '💰', keywords: 'money bag dollar' },
      { emoji: '🪙', keywords: 'coin money' },
      { emoji: '💴', keywords: 'yen banknote money' },
      { emoji: '💵', keywords: 'dollar banknote money' },
      { emoji: '💶', keywords: 'euro banknote money' },
      { emoji: '💷', keywords: 'pound banknote money' },
      { emoji: '💸', keywords: 'money wings flying' },
      { emoji: '💳', keywords: 'credit card payment' },
      { emoji: '🧾', keywords: 'receipt' },
      { emoji: '💹', keywords: 'chart increasing yen' },
      { emoji: '✉️', keywords: 'envelope email letter mail' },
      { emoji: '📧', keywords: 'email e-mail' },
      { emoji: '📨', keywords: 'incoming envelope email' },
      { emoji: '📩', keywords: 'envelope arrow email' },
      { emoji: '📤', keywords: 'outbox tray' },
      { emoji: '📥', keywords: 'inbox tray' },
      { emoji: '📦', keywords: 'package box delivery' },
      { emoji: '📫', keywords: 'closed mailbox flag up' },
      { emoji: '📪', keywords: 'closed mailbox flag down' },
      { emoji: '📬', keywords: 'open mailbox flag up' },
      { emoji: '📭', keywords: 'open mailbox flag down' },
      { emoji: '📮', keywords: 'postbox mailbox' },
      { emoji: '🗳️', keywords: 'ballot box vote' },
      { emoji: '✏️', keywords: 'pencil write' },
      { emoji: '✒️', keywords: 'black nib pen' },
      { emoji: '🖋️', keywords: 'fountain pen write' },
      { emoji: '🖊️', keywords: 'pen write' },
      { emoji: '🖌️', keywords: 'paintbrush art' },
      { emoji: '🖍️', keywords: 'crayon draw' },
      { emoji: '📝', keywords: 'memo note write' },
      { emoji: '💼', keywords: 'briefcase business work' },
      { emoji: '📁', keywords: 'file folder directory' },
      { emoji: '📂', keywords: 'open file folder' },
      { emoji: '🗂️', keywords: 'card index dividers' },
      { emoji: '📅', keywords: 'calendar date' },
      { emoji: '📆', keywords: 'tear off calendar' },
      { emoji: '🗒️', keywords: 'spiral notepad' },
      { emoji: '🗓️', keywords: 'spiral calendar' },
      { emoji: '📇', keywords: 'card index' },
      { emoji: '📈', keywords: 'chart increasing up' },
      { emoji: '📉', keywords: 'chart decreasing down' },
      { emoji: '📊', keywords: 'bar chart graph' },
      { emoji: '📋', keywords: 'clipboard' },
      { emoji: '📌', keywords: 'pushpin pin' },
      { emoji: '📍', keywords: 'round pushpin location' },
      { emoji: '📎', keywords: 'paperclip' },
      { emoji: '🖇️', keywords: 'linked paperclips' },
      { emoji: '📏', keywords: 'straight ruler measure' },
      { emoji: '📐', keywords: 'triangular ruler measure' },
      { emoji: '✂️', keywords: 'scissors cut' },
      { emoji: '🗃️', keywords: 'card file box' },
      { emoji: '🗄️', keywords: 'file cabinet' },
      { emoji: '🗑️', keywords: 'wastebasket trash delete' },
      { emoji: '🔒', keywords: 'locked padlock secure' },
      { emoji: '🔓', keywords: 'unlocked padlock open' },
      { emoji: '🔏', keywords: 'locked pen secure' },
      { emoji: '🔐', keywords: 'locked key secure' },
      { emoji: '🔑', keywords: 'key password access' },
      { emoji: '🗝️', keywords: 'old key vintage' },
      { emoji: '🔨', keywords: 'hammer tool' },
      { emoji: '🪓', keywords: 'axe chop' },
      { emoji: '⛏️', keywords: 'pick mining' },
      { emoji: '⚒️', keywords: 'hammer pick tools' },
      { emoji: '🛠️', keywords: 'hammer wrench tools' },
      { emoji: '🗡️', keywords: 'dagger knife sword' },
      { emoji: '⚔️', keywords: 'crossed swords battle' },
      { emoji: '🔫', keywords: 'pistol gun water' },
      { emoji: '🪃', keywords: 'boomerang australia' },
      { emoji: '🏹', keywords: 'bow arrow archery' },
      { emoji: '🛡️', keywords: 'shield protect defense' },
      { emoji: '🪚', keywords: 'carpentry saw cut' },
      { emoji: '🔧', keywords: 'wrench tool spanner' },
      { emoji: '🪛', keywords: 'screwdriver tool' },
      { emoji: '🔩', keywords: 'nut bolt screw' },
      { emoji: '⚙️', keywords: 'gear cog settings' },
      { emoji: '🗜️', keywords: 'clamp compress' },
      { emoji: '⚖️', keywords: 'balance scale justice' },
      { emoji: '🦯', keywords: 'white cane blind' },
      { emoji: '🔗', keywords: 'link chain url' },
      { emoji: '⛓️', keywords: 'chains' },
      { emoji: '🪝', keywords: 'hook' },
      { emoji: '🧰', keywords: 'toolbox tools' },
      { emoji: '🧲', keywords: 'magnet attract' },
      { emoji: '🪜', keywords: 'ladder climb' },
      { emoji: '⚗️', keywords: 'alembic chemistry science' },
      { emoji: '🧪', keywords: 'test tube science' },
      { emoji: '🧫', keywords: 'petri dish bacteria' },
      { emoji: '🧬', keywords: 'dna genetics' },
      { emoji: '🔬', keywords: 'microscope science' },
      { emoji: '🔭', keywords: 'telescope astronomy' },
      { emoji: '📡', keywords: 'satellite antenna dish' },
      { emoji: '💉', keywords: 'syringe needle vaccine' },
      { emoji: '🩸', keywords: 'drop blood donate' },
      { emoji: '💊', keywords: 'pill medicine drug' },
      { emoji: '🩹', keywords: 'adhesive bandage bandaid' },
      { emoji: '🩺', keywords: 'stethoscope doctor medical' },
      { emoji: '🚪', keywords: 'door entrance exit' },
      { emoji: '🛗', keywords: 'elevator lift' },
      { emoji: '🪞', keywords: 'mirror reflection' },
      { emoji: '🪟', keywords: 'window' },
      { emoji: '🛏️', keywords: 'bed sleep' },
      { emoji: '🛋️', keywords: 'couch sofa lamp' },
      { emoji: '🪑', keywords: 'chair seat' },
      { emoji: '🚽', keywords: 'toilet bathroom' },
      { emoji: '🪠', keywords: 'plunger bathroom' },
      { emoji: '🚿', keywords: 'shower bathroom' },
      { emoji: '🛁', keywords: 'bathtub bath' },
      { emoji: '🪤', keywords: 'mouse trap' },
      { emoji: '🪒', keywords: 'razor shave' },
      { emoji: '🧴', keywords: 'lotion bottle' },
      { emoji: '🧷', keywords: 'safety pin' },
      { emoji: '🧹', keywords: 'broom sweep clean' },
      { emoji: '🧺', keywords: 'basket laundry' },
      { emoji: '🧻', keywords: 'roll paper toilet' },
      { emoji: '🪣', keywords: 'bucket pail' },
      { emoji: '🧼', keywords: 'soap clean wash' },
      { emoji: '🪥', keywords: 'toothbrush dental' },
      { emoji: '🧽', keywords: 'sponge clean' },
      { emoji: '🧯', keywords: 'fire extinguisher' },
      { emoji: '🛒', keywords: 'shopping cart trolley' },
      { emoji: '🚬', keywords: 'cigarette smoking' },
      { emoji: '⚰️', keywords: 'coffin death funeral' },
      { emoji: '🪦', keywords: 'headstone grave cemetery' },
      { emoji: '⚱️', keywords: 'funeral urn ashes' },
      { emoji: '🗿', keywords: 'moai statue easter island' },
      { emoji: '🪧', keywords: 'placard sign protest' },
    ],
  },
  {
    name: 'Symbols',
    icon: '❤️',
    emojis: [
      { emoji: '❤️', keywords: 'red heart love' },
      { emoji: '🧡', keywords: 'orange heart love' },
      { emoji: '💛', keywords: 'yellow heart love' },
      { emoji: '💚', keywords: 'green heart love' },
      { emoji: '💙', keywords: 'blue heart love' },
      { emoji: '💜', keywords: 'purple heart love' },
      { emoji: '🖤', keywords: 'black heart love' },
      { emoji: '🤍', keywords: 'white heart love' },
      { emoji: '🤎', keywords: 'brown heart love' },
      { emoji: '💔', keywords: 'broken heart sad' },
      { emoji: '❣️', keywords: 'heart exclamation love' },
      { emoji: '💕', keywords: 'two hearts love' },
      { emoji: '💞', keywords: 'revolving hearts love' },
      { emoji: '💓', keywords: 'beating heart love' },
      { emoji: '💗', keywords: 'growing heart love' },
      { emoji: '💖', keywords: 'sparkling heart love' },
      { emoji: '💘', keywords: 'heart arrow cupid love' },
      { emoji: '💝', keywords: 'heart ribbon gift love' },
      { emoji: '💟', keywords: 'heart decoration love' },
      { emoji: '☮️', keywords: 'peace symbol' },
      { emoji: '✝️', keywords: 'latin cross christian' },
      { emoji: '☪️', keywords: 'star crescent islam' },
      { emoji: '🕉️', keywords: 'om hindu' },
      { emoji: '☸️', keywords: 'wheel dharma buddhism' },
      { emoji: '✡️', keywords: 'star david jewish' },
      { emoji: '🔯', keywords: 'six pointed star' },
      { emoji: '🕎', keywords: 'menorah jewish' },
      { emoji: '☯️', keywords: 'yin yang balance' },
      { emoji: '☦️', keywords: 'orthodox cross' },
      { emoji: '🛐', keywords: 'place worship religion' },
      { emoji: '⛎', keywords: 'ophiuchus zodiac' },
      { emoji: '♈', keywords: 'aries zodiac' },
      { emoji: '♉', keywords: 'taurus zodiac' },
      { emoji: '♊', keywords: 'gemini zodiac' },
      { emoji: '♋', keywords: 'cancer zodiac' },
      { emoji: '♌', keywords: 'leo zodiac' },
      { emoji: '♍', keywords: 'virgo zodiac' },
      { emoji: '♎', keywords: 'libra zodiac' },
      { emoji: '♏', keywords: 'scorpio zodiac' },
      { emoji: '♐', keywords: 'sagittarius zodiac' },
      { emoji: '♑', keywords: 'capricorn zodiac' },
      { emoji: '♒', keywords: 'aquarius zodiac' },
      { emoji: '♓', keywords: 'pisces zodiac' },
      { emoji: '🆔', keywords: 'id identity' },
      { emoji: '⚛️', keywords: 'atom symbol science' },
      { emoji: '🉑', keywords: 'japanese acceptable' },
      { emoji: '☢️', keywords: 'radioactive nuclear' },
      { emoji: '☣️', keywords: 'biohazard biological' },
      { emoji: '📴', keywords: 'mobile phone off' },
      { emoji: '📳', keywords: 'vibration mode phone' },
      { emoji: '🈶', keywords: 'japanese have' },
      { emoji: '🈚', keywords: 'japanese free charge' },
      { emoji: '🈸', keywords: 'japanese application' },
      { emoji: '🈺', keywords: 'japanese open business' },
      { emoji: '🈷️', keywords: 'japanese monthly' },
      { emoji: '✴️', keywords: 'eight pointed star' },
      { emoji: '🆚', keywords: 'vs versus' },
      { emoji: '💮', keywords: 'white flower' },
      { emoji: '🉐', keywords: 'japanese bargain' },
      { emoji: '㊙️', keywords: 'japanese secret' },
      { emoji: '㊗️', keywords: 'japanese congratulations' },
      { emoji: '🈴', keywords: 'japanese passing grade' },
      { emoji: '🈵', keywords: 'japanese no vacancy' },
      { emoji: '🈹', keywords: 'japanese discount' },
      { emoji: '🈲', keywords: 'japanese prohibited' },
      { emoji: '🅰️', keywords: 'a button blood type' },
      { emoji: '🅱️', keywords: 'b button blood type' },
      { emoji: '🆎', keywords: 'ab button blood type' },
      { emoji: '🆑', keywords: 'cl button' },
      { emoji: '🅾️', keywords: 'o button blood type' },
      { emoji: '🆘', keywords: 'sos help emergency' },
      { emoji: '❌', keywords: 'cross mark x wrong' },
      { emoji: '⭕', keywords: 'hollow red circle' },
      { emoji: '🛑', keywords: 'stop sign octagon' },
      { emoji: '⛔', keywords: 'no entry prohibited' },
      { emoji: '📛', keywords: 'name badge' },
      { emoji: '🚫', keywords: 'prohibited forbidden no' },
      { emoji: '💯', keywords: 'hundred points score' },
      { emoji: '💢', keywords: 'anger symbol mad' },
      { emoji: '♨️', keywords: 'hot springs' },
      { emoji: '🚷', keywords: 'no pedestrians' },
      { emoji: '🚯', keywords: 'no littering' },
      { emoji: '🚳', keywords: 'no bicycles' },
      { emoji: '🚱', keywords: 'non potable water' },
      { emoji: '🔞', keywords: 'no one under eighteen adult' },
      { emoji: '📵', keywords: 'no mobile phones' },
      { emoji: '🚭', keywords: 'no smoking' },
      { emoji: '❗', keywords: 'exclamation mark warning' },
      { emoji: '❕', keywords: 'white exclamation mark' },
      { emoji: '❓', keywords: 'question mark' },
      { emoji: '❔', keywords: 'white question mark' },
      { emoji: '‼️', keywords: 'double exclamation mark' },
      { emoji: '⁉️', keywords: 'exclamation question mark' },
      { emoji: '🔅', keywords: 'dim button brightness' },
      { emoji: '🔆', keywords: 'bright button brightness' },
      { emoji: '〽️', keywords: 'part alternation mark' },
      { emoji: '⚠️', keywords: 'warning sign caution' },
      { emoji: '🚸', keywords: 'children crossing' },
      { emoji: '🔱', keywords: 'trident emblem' },
      { emoji: '⚜️', keywords: 'fleur de lis' },
      { emoji: '🔰', keywords: 'japanese symbol beginner' },
      { emoji: '♻️', keywords: 'recycling symbol recycle' },
      { emoji: '✅', keywords: 'check mark button yes' },
      { emoji: '🈯', keywords: 'japanese reserved' },
      { emoji: '💹', keywords: 'chart increasing yen' },
      { emoji: '❇️', keywords: 'sparkle star' },
      { emoji: '✳️', keywords: 'eight spoked asterisk' },
      { emoji: '❎', keywords: 'cross mark button' },
      { emoji: '🌐', keywords: 'globe meridians web internet' },
      { emoji: '💠', keywords: 'diamond dot cute' },
      { emoji: 'Ⓜ️', keywords: 'circled m metro' },
      { emoji: '🌀', keywords: 'cyclone spiral hurricane' },
      { emoji: '💤', keywords: 'zzz sleep tired' },
      { emoji: '🏧', keywords: 'atm sign' },
      { emoji: '🚾', keywords: 'water closet toilet' },
      { emoji: '♿', keywords: 'wheelchair symbol accessible' },
      { emoji: '🅿️', keywords: 'p button parking' },
      { emoji: '🛗', keywords: 'elevator' },
      { emoji: '🈳', keywords: 'japanese vacancy' },
      { emoji: '🈂️', keywords: 'japanese service charge' },
      { emoji: '🛂', keywords: 'passport control' },
      { emoji: '🛃', keywords: 'customs' },
      { emoji: '🛄', keywords: 'baggage claim' },
      { emoji: '🛅', keywords: 'left luggage' },
      { emoji: '🚹', keywords: 'mens room restroom' },
      { emoji: '🚺', keywords: 'womens room restroom' },
      { emoji: '🚼', keywords: 'baby symbol' },
      { emoji: '⚧️', keywords: 'transgender symbol' },
      { emoji: '🚻', keywords: 'restroom bathroom' },
      { emoji: '🚮', keywords: 'litter bin sign' },
      { emoji: '🎦', keywords: 'cinema movies' },
      { emoji: '📶', keywords: 'signal strength bars' },
      { emoji: '🈁', keywords: 'japanese here' },
      { emoji: '🔣', keywords: 'input symbols' },
      { emoji: 'ℹ️', keywords: 'information source' },
      { emoji: '🔤', keywords: 'input latin letters abc' },
      { emoji: '🔡', keywords: 'input latin lowercase' },
      { emoji: '🔠', keywords: 'input latin uppercase' },
      { emoji: '🆖', keywords: 'ng button' },
      { emoji: '🆗', keywords: 'ok button' },
      { emoji: '🆙', keywords: 'up button' },
      { emoji: '🆒', keywords: 'cool button' },
      { emoji: '🆕', keywords: 'new button' },
      { emoji: '🆓', keywords: 'free button' },
      { emoji: '0️⃣', keywords: 'keycap 0 zero' },
      { emoji: '1️⃣', keywords: 'keycap 1 one' },
      { emoji: '2️⃣', keywords: 'keycap 2 two' },
      { emoji: '3️⃣', keywords: 'keycap 3 three' },
      { emoji: '4️⃣', keywords: 'keycap 4 four' },
      { emoji: '5️⃣', keywords: 'keycap 5 five' },
      { emoji: '6️⃣', keywords: 'keycap 6 six' },
      { emoji: '7️⃣', keywords: 'keycap 7 seven' },
      { emoji: '8️⃣', keywords: 'keycap 8 eight' },
      { emoji: '9️⃣', keywords: 'keycap 9 nine' },
      { emoji: '🔟', keywords: 'keycap 10 ten' },
      { emoji: '🔢', keywords: 'input numbers 1234' },
      { emoji: '#️⃣', keywords: 'keycap hash pound' },
      { emoji: '*️⃣', keywords: 'keycap asterisk star' },
      { emoji: '⏏️', keywords: 'eject button' },
      { emoji: '▶️', keywords: 'play button' },
      { emoji: '⏸️', keywords: 'pause button' },
      { emoji: '⏯️', keywords: 'play pause button' },
      { emoji: '⏹️', keywords: 'stop button' },
      { emoji: '⏺️', keywords: 'record button' },
      { emoji: '⏭️', keywords: 'next track button' },
      { emoji: '⏮️', keywords: 'last track button' },
      { emoji: '⏩', keywords: 'fast forward button' },
      { emoji: '⏪', keywords: 'fast reverse button' },
      { emoji: '⏫', keywords: 'fast up button' },
      { emoji: '⏬', keywords: 'fast down button' },
      { emoji: '◀️', keywords: 'reverse button back' },
      { emoji: '🔼', keywords: 'upwards button' },
      { emoji: '🔽', keywords: 'downwards button' },
      { emoji: '➡️', keywords: 'right arrow' },
      { emoji: '⬅️', keywords: 'left arrow' },
      { emoji: '⬆️', keywords: 'up arrow' },
      { emoji: '⬇️', keywords: 'down arrow' },
      { emoji: '↗️', keywords: 'up right arrow' },
      { emoji: '↘️', keywords: 'down right arrow' },
      { emoji: '↙️', keywords: 'down left arrow' },
      { emoji: '↖️', keywords: 'up left arrow' },
      { emoji: '↕️', keywords: 'up down arrow' },
      { emoji: '↔️', keywords: 'left right arrow' },
      { emoji: '↪️', keywords: 'right arrow curving left' },
      { emoji: '↩️', keywords: 'left arrow curving right' },
      { emoji: '⤴️', keywords: 'right arrow curving up' },
      { emoji: '⤵️', keywords: 'right arrow curving down' },
      { emoji: '🔀', keywords: 'shuffle tracks button' },
      { emoji: '🔁', keywords: 'repeat button loop' },
      { emoji: '🔂', keywords: 'repeat single button' },
      { emoji: '🔄', keywords: 'counterclockwise arrows refresh' },
      { emoji: '🔃', keywords: 'clockwise arrows reload' },
      { emoji: '🎵', keywords: 'musical note music' },
      { emoji: '🎶', keywords: 'musical notes music' },
      { emoji: '➕', keywords: 'plus sign add' },
      { emoji: '➖', keywords: 'minus sign subtract' },
      { emoji: '➗', keywords: 'division sign divide' },
      { emoji: '✖️', keywords: 'multiplication sign multiply' },
      { emoji: '♾️', keywords: 'infinity forever' },
      { emoji: '💲', keywords: 'heavy dollar sign money' },
      { emoji: '💱', keywords: 'currency exchange money' },
      { emoji: '™️', keywords: 'trade mark' },
      { emoji: '©️', keywords: 'copyright' },
      { emoji: '®️', keywords: 'registered' },
      { emoji: '〰️', keywords: 'wavy dash' },
      { emoji: '➰', keywords: 'curly loop' },
      { emoji: '➿', keywords: 'double curly loop' },
      { emoji: '🔚', keywords: 'end arrow' },
      { emoji: '🔙', keywords: 'back arrow' },
      { emoji: '🔛', keywords: 'on arrow' },
      { emoji: '🔝', keywords: 'top arrow' },
      { emoji: '🔜', keywords: 'soon arrow' },
      { emoji: '✔️', keywords: 'check mark yes done' },
      { emoji: '☑️', keywords: 'check box vote' },
      { emoji: '🔘', keywords: 'radio button' },
      { emoji: '🔴', keywords: 'red circle' },
      { emoji: '🟠', keywords: 'orange circle' },
      { emoji: '🟡', keywords: 'yellow circle' },
      { emoji: '🟢', keywords: 'green circle' },
      { emoji: '🔵', keywords: 'blue circle' },
      { emoji: '🟣', keywords: 'purple circle' },
      { emoji: '🟤', keywords: 'brown circle' },
      { emoji: '⚫', keywords: 'black circle' },
      { emoji: '⚪', keywords: 'white circle' },
      { emoji: '🟥', keywords: 'red square' },
      { emoji: '🟧', keywords: 'orange square' },
      { emoji: '🟨', keywords: 'yellow square' },
      { emoji: '🟩', keywords: 'green square' },
      { emoji: '🟦', keywords: 'blue square' },
      { emoji: '🟪', keywords: 'purple square' },
      { emoji: '🟫', keywords: 'brown square' },
      { emoji: '⬛', keywords: 'black large square' },
      { emoji: '⬜', keywords: 'white large square' },
      { emoji: '◼️', keywords: 'black medium square' },
      { emoji: '◻️', keywords: 'white medium square' },
      { emoji: '◾', keywords: 'black medium small square' },
      { emoji: '◽', keywords: 'white medium small square' },
      { emoji: '▪️', keywords: 'black small square' },
      { emoji: '▫️', keywords: 'white small square' },
      { emoji: '🔶', keywords: 'large orange diamond' },
      { emoji: '🔷', keywords: 'large blue diamond' },
      { emoji: '🔸', keywords: 'small orange diamond' },
      { emoji: '🔹', keywords: 'small blue diamond' },
      { emoji: '🔺', keywords: 'red triangle pointed up' },
      { emoji: '🔻', keywords: 'red triangle pointed down' },
      { emoji: '💎', keywords: 'gem stone diamond jewel' },
      { emoji: '🔲', keywords: 'black square button' },
      { emoji: '🔳', keywords: 'white square button' },
      { emoji: '🔈', keywords: 'speaker low volume' },
      { emoji: '🔉', keywords: 'speaker medium volume' },
      { emoji: '🔊', keywords: 'speaker high volume loud' },
      { emoji: '🔇', keywords: 'muted speaker no sound' },
      { emoji: '📣', keywords: 'megaphone cheering' },
      { emoji: '📢', keywords: 'loudspeaker public address' },
      { emoji: '🔔', keywords: 'bell notification' },
      { emoji: '🔕', keywords: 'bell slash no notification' },
    ],
  },
  {
    name: 'Flags',
    icon: '🏳️',
    emojis: [
      { emoji: '🏳️', keywords: 'white flag surrender' },
      { emoji: '🏴', keywords: 'black flag' },
      { emoji: '🏁', keywords: 'chequered flag racing finish' },
      { emoji: '🚩', keywords: 'triangular flag red' },
      { emoji: '🏳️‍🌈', keywords: 'rainbow flag pride lgbtq' },
      { emoji: '🏳️‍⚧️', keywords: 'transgender flag pride' },
      { emoji: '🏴‍☠️', keywords: 'pirate flag jolly roger' },
      { emoji: '🇦🇫', keywords: 'flag afghanistan' },
      { emoji: '🇦🇱', keywords: 'flag albania' },
      { emoji: '🇩🇿', keywords: 'flag algeria' },
      { emoji: '🇦🇷', keywords: 'flag argentina' },
      { emoji: '🇦🇺', keywords: 'flag australia' },
      { emoji: '🇦🇹', keywords: 'flag austria' },
      { emoji: '🇧🇪', keywords: 'flag belgium' },
      { emoji: '🇧🇷', keywords: 'flag brazil' },
      { emoji: '🇨🇦', keywords: 'flag canada' },
      { emoji: '🇨🇱', keywords: 'flag chile' },
      { emoji: '🇨🇳', keywords: 'flag china' },
      { emoji: '🇨🇴', keywords: 'flag colombia' },
      { emoji: '🇭🇷', keywords: 'flag croatia' },
      { emoji: '🇨🇺', keywords: 'flag cuba' },
      { emoji: '🇨🇿', keywords: 'flag czech republic czechia' },
      { emoji: '🇩🇰', keywords: 'flag denmark' },
      { emoji: '🇪🇬', keywords: 'flag egypt' },
      { emoji: '🇫🇮', keywords: 'flag finland' },
      { emoji: '🇫🇷', keywords: 'flag france' },
      { emoji: '🇩🇪', keywords: 'flag germany' },
      { emoji: '🇬🇷', keywords: 'flag greece' },
      { emoji: '🇭🇰', keywords: 'flag hong kong' },
      { emoji: '🇭🇺', keywords: 'flag hungary' },
      { emoji: '🇮🇸', keywords: 'flag iceland' },
      { emoji: '🇮🇳', keywords: 'flag india' },
      { emoji: '🇮🇩', keywords: 'flag indonesia' },
      { emoji: '🇮🇪', keywords: 'flag ireland' },
      { emoji: '🇮🇱', keywords: 'flag israel' },
      { emoji: '🇮🇹', keywords: 'flag italy' },
      { emoji: '🇯🇵', keywords: 'flag japan' },
      { emoji: '🇰🇪', keywords: 'flag kenya' },
      { emoji: '🇰🇷', keywords: 'flag south korea' },
      { emoji: '🇲🇾', keywords: 'flag malaysia' },
      { emoji: '🇲🇽', keywords: 'flag mexico' },
      { emoji: '🇳🇱', keywords: 'flag netherlands' },
      { emoji: '🇳🇿', keywords: 'flag new zealand' },
      { emoji: '🇳🇬', keywords: 'flag nigeria' },
      { emoji: '🇳🇴', keywords: 'flag norway' },
      { emoji: '🇵🇰', keywords: 'flag pakistan' },
      { emoji: '🇵🇪', keywords: 'flag peru' },
      { emoji: '🇵🇭', keywords: 'flag philippines' },
      { emoji: '🇵🇱', keywords: 'flag poland' },
      { emoji: '🇵🇹', keywords: 'flag portugal' },
      { emoji: '🇷🇴', keywords: 'flag romania' },
      { emoji: '🇷🇺', keywords: 'flag russia' },
      { emoji: '🇸🇦', keywords: 'flag saudi arabia' },
      { emoji: '🇸🇬', keywords: 'flag singapore' },
      { emoji: '🇿🇦', keywords: 'flag south africa' },
      { emoji: '🇪🇸', keywords: 'flag spain' },
      { emoji: '🇸🇪', keywords: 'flag sweden' },
      { emoji: '🇨🇭', keywords: 'flag switzerland' },
      { emoji: '🇹🇼', keywords: 'flag taiwan' },
      { emoji: '🇹🇭', keywords: 'flag thailand' },
      { emoji: '🇹🇷', keywords: 'flag turkey' },
      { emoji: '🇺🇦', keywords: 'flag ukraine' },
      { emoji: '🇦🇪', keywords: 'flag united arab emirates uae' },
      { emoji: '🇬🇧', keywords: 'flag united kingdom uk britain' },
      { emoji: '🇺🇸', keywords: 'flag united states usa america' },
      { emoji: '🇻🇳', keywords: 'flag vietnam' },
    ],
  },
]

// Flat list of all emojis for search
export const ALL_EMOJIS = EMOJI_CATEGORIES.flatMap(cat => cat.emojis)
